package euler;

/**
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class EvenFibonacciNumbers {

    public static void main(String[] args) {
        int maximum = 4000000;

        int sum = 0;
        int first = 1, second = 1, third = first + second;

        while (third < maximum) {
            sum += third;
            first = second + third;
            second = third + first;
            third = first + second;
        }

        System.out.println("Sum = " + sum);
    }
}